apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: sy7k2cafa-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-076d863d96.c7mj.p3.openshiftapps.com/rhtap/rhtap-qe:997fc788b1a86b446845cce1d5d218ef2510c837@sha256:5b39fa86731995ac3c7469ced05cfd09f6fe85d985e9484b30eae04ad8a95d77
        name: container-image  
